### ISSUE TITLE
Mac OS Mojave Compatibility

### ISSUE THREAD

**Issue by mistapinguin** [JorritPosthuma/MixCloud-Desktop#17]
Software is crashing on Mojave.
Please fix :(

**Comment by TheSpyder** [comment]
Sorry, I've had a rough month or so and been off work with medical leave. I'm upgrading to Mojave today, and will look at all the issues with this app as soon as I can.

**Comment by TheSpyder** [comment]
Looks like the crash is due to an assertion that media keys are working, but that needs accessibility permissions now. I've already fixed the crash in my local dev environment but I'm not sure whether I can make that whole process work as Apple intended. I had to enable it and then restart the app.

Certainly once it has permission the app seems to work as before without issue.

**Comment by TheSpyder** [comment]
I've published a new build. Hopefully that helps.

**Comment by pkruithof** [comment]
Thank you @TheSpyder! 

I think this app is wonderful, as I hate browser tabs with playing audio.

**Comment by uffou** [comment]
Made an electron MixClould app - support for tracks in the menubar, media controls and notifications https://github.com/uffou/MixCloud-Play

**Comment by TheSpyder** [comment]
@uffou Looks great! Nice work! I'll update the readme to make it official that this project is abandoned and link to your project instead.
